# Generated by Django 3.2 on 2023-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appuser',
            name='city',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_pic',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
